version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    ports:
      - '27017:27017'
volumes:
  mongodb_data:
